---
deployment:
  tasks:
    - export DEPLOYPATH=/home/capnachi/noitruxinman.edu.vn/pccm/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/rsync -av --delete --exclude=".git" --exclude=".cpanel.yml" ./ $DEPLOYPATH
    - /bin/chmod -R 755 $DEPLOYPATH
    - /bin/chmod -R 777 $DEPLOYPATH/data
